name: Lint and Test

on:
  pull_request:

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Use Node.js 18.8.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.8.x'
      - name: yarn install
        run: yarn install
      - name: yarn build
        run: yarn build
      - name: yarn lint
        run: yarn lint
      - name: yarn ts:check
        run: yarn ts:check
      - name: yarn test:unit
        run: yarn test:unit
  e2e:
    runs-on: ubuntu-latest
    services:
      agoric:
        image: ghcr.io/agoric/agoric-3-proposals:main # fork of agoric-3
        ports:
          - 1317:1317 # api port
          - 26657:26657 # rpc port
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Use Node.js 18.8.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.8.x'
      - name: yarn install
        run: yarn install
      - name: Install jq
        run: sudo apt-get install jq
      - name: Wait for Docker container to be ready
        run: |
          timeout 300 bash -c '
          echo "Waiting for the agoric service to be ready...";
          while true; do
            response=$(curl --silent http://localhost:1317);
            echo "Checking service response: $response";
            code=$(echo $response | jq .code);
            message=$(echo $response | jq -r .message);
            if [ "$code" == "12" ] && [ "$message" == "Not Implemented" ]; then
              echo "Service is ready!";
              break;
            fi;
            sleep 10;
            timeout=$((timeout-10));
            if [ "$timeout" -le 0 ]; then
              echo "Service did not become ready in time";
              exit 1;
            fi;
          done'
      - name: Run E2E Tests
        run: yarn test:e2e
